/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/artifacts/status': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get remote caching status
     * @description Check the status of Remote Caching for the authenticated user or team. Returns a JSON-encoded status indicating if Remote Caching is enabled, disabled, or disabled due to usage limits.
     *
     *     Implementers should return `enabled` if the authenticated principal is allowed to use the cache, or `disabled` if not. The `over_limit` and `paused` statuses are optional and can be used to indicate usage limits or temporary suspension.
     */
    get: operations['getArtifactStatus'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/artifacts/{hash}': {
    parameters: {
      query?: {
        /** @description The team identifier to perform the request on behalf of. Used for multi-tenant cache implementations where artifacts are scoped to teams. */
        teamId?: components['parameters']['TeamId'];
        /** @description The team slug to perform the request on behalf of. Alternative to `teamId` for identifying the team. */
        slug?: components['parameters']['Slug'];
      };
      header?: never;
      path: {
        /** @description The artifact hash. This is a content-addressable hash that uniquely identifies the cached artifact based on task inputs. */
        hash: components['parameters']['ArtifactHash'];
      };
      cookie?: never;
    };
    /**
     * Download a cache artifact
     * @description Downloads a cache artifact identified by its `hash` specified on the request path. The artifact is downloaded as an octet-stream (binary data).
     *
     *     The artifact data is a gzip-compressed tarball containing the cached task outputs. The client will verify the content-length header against the response body size.
     */
    get: operations['downloadArtifact'];
    /**
     * Upload a cache artifact
     * @description Uploads a cache artifact identified by the `hash` specified on the path. The cache artifact can then be downloaded with the provided `hash`.
     *
     *     The request body should contain a gzip-compressed tarball of the task outputs. The server should store this data and make it available for subsequent downloads.
     */
    put: operations['uploadArtifact'];
    post?: never;
    delete?: never;
    options?: never;
    /**
     * Check if artifact exists
     * @description Check that a cache artifact with the given `hash` exists. This request returns response headers only and is equivalent to a `GET` request to this endpoint where the response contains no body.
     *
     *     Implementers should return 200 if the artifact exists, or 404 if it does not.
     */
    head: operations['artifactExists'];
    patch?: never;
    trace?: never;
  };
  '/artifacts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Query artifact information
     * @description Query information about multiple artifacts by their hashes. Returns metadata about each artifact including size, task duration, and tag.
     *
     *     This endpoint is optional for basic cache functionality but enables optimized cache fetching by allowing the client to query multiple artifacts in a single request.
     */
    post: operations['queryArtifacts'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/artifacts/events': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Record cache usage events
     * @description Records cache usage analytics events. The body of this request is an array of cache usage events.
     *
     *     This endpoint is optional but enables cache hit/miss analytics. Implementers can use this data to track cache effectiveness and optimize storage.
     *
     *     Event types:
     *     - `HIT`: A cached artifact was found and used
     *     - `MISS`: No cached artifact was found for the given hash
     *
     *     Source types:
     *     - `LOCAL`: The cache event was on the user's local filesystem cache
     *     - `REMOTE`: The cache event is for the remote cache
     */
    post: operations['recordCacheEvents'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * @description The status of remote caching for the authenticated principal.
     *
     *     - `enabled`: Remote caching is enabled and available
     *     - `disabled`: Remote caching is disabled
     *     - `over_limit`: Remote caching is disabled due to usage limits (optional)
     *     - `paused`: Remote caching is temporarily paused (optional)
     * @enum {string}
     */
    CachingStatus: 'disabled' | 'enabled' | 'over_limit' | 'paused';
    CachingStatusResponse: {
      status: components['schemas']['CachingStatus'];
    };
    ArtifactUploadResponse: {
      /** @description Array of URLs where the artifact was stored. Implementers can return the storage location(s) for debugging purposes. */
      urls: string[];
    };
    ArtifactQueryRequest: {
      /** @description Array of artifact hashes to query */
      hashes: string[];
    };
    /** @description A map of artifact hashes to their information. The value is `null` if the artifact was not found. */
    ArtifactQueryResponse: {
      [key: string]:
        | (
            | components['schemas']['ArtifactInfo']
            | components['schemas']['ArtifactError']
          )
        | null;
    };
    ArtifactInfo: {
      /** @description The size of the artifact in bytes */
      size: number;
      /** @description The time taken to generate the artifact in milliseconds */
      taskDurationMs: number;
      /** @description The artifact tag/signature for verification */
      tag?: string;
    };
    ArtifactError: {
      error: {
        /** @description Error message describing why the artifact information could not be retrieved */
        message: string;
      };
    };
    CacheEvent: {
      /**
       * Format: uuid
       * @description A UUID that identifies the Turborepo session that generated this event
       */
      sessionId: string;
      /**
       * @description The source of the cache event.
       *
       *     - `LOCAL`: The event occurred on the user's local filesystem cache
       *     - `REMOTE`: The event is for the remote cache
       * @enum {string}
       */
      source: 'LOCAL' | 'REMOTE';
      /**
       * @description The type of cache event.
       *
       *     - `HIT`: A cached artifact was found
       *     - `MISS`: No cached artifact was found
       * @enum {string}
       */
      event: 'HIT' | 'MISS';
      /** @description The artifact hash associated with this event */
      hash: string;
      /** @description The time taken to generate the artifact in milliseconds. Only meaningful for `HIT` events. */
      duration?: number;
    };
    Error: {
      /** @description A machine-readable error code */
      code: string;
      /** @description A human-readable error message */
      message: string;
    };
  };
  responses: {
    /** @description Bad request. One or more of the provided values in the request query, headers, or body is invalid. */
    BadRequest: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['Error'];
      };
    };
    /** @description Unauthorized. The request is missing a valid authentication token or the token is invalid. */
    Unauthorized: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['Error'];
      };
    };
    /** @description Forbidden. The authenticated user does not have permission to access this resource. */
    Forbidden: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['Error'];
      };
    };
    /** @description Artifact not found. No artifact with the specified hash exists. */
    ArtifactNotFound: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['Error'];
      };
    };
  };
  parameters: {
    /** @description The artifact hash. This is a content-addressable hash that uniquely identifies the cached artifact based on task inputs. */
    ArtifactHash: string;
    /** @description The team identifier to perform the request on behalf of. Used for multi-tenant cache implementations where artifacts are scoped to teams. */
    TeamId: string;
    /** @description The team slug to perform the request on behalf of. Alternative to `teamId` for identifying the team. */
    Slug: string;
    /** @description The continuous integration or delivery environment where this artifact operation is being performed. Examples: `github-actions`, `circleci`, `jenkins`. */
    ArtifactClientCI: string;
    /** @description Indicates whether the client is running in an interactive shell. `1` for interactive, `0` for non-interactive (CI/scripts). */
    ArtifactClientInteractive: 0 | 1;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getArtifactStatus: {
    parameters: {
      query?: {
        /** @description The team identifier to perform the request on behalf of. Used for multi-tenant cache implementations where artifacts are scoped to teams. */
        teamId?: components['parameters']['TeamId'];
        /** @description The team slug to perform the request on behalf of. Alternative to `teamId` for identifying the team. */
        slug?: components['parameters']['Slug'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Remote caching status retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CachingStatusResponse'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
    };
  };
  downloadArtifact: {
    parameters: {
      query?: {
        /** @description The team identifier to perform the request on behalf of. Used for multi-tenant cache implementations where artifacts are scoped to teams. */
        teamId?: components['parameters']['TeamId'];
        /** @description The team slug to perform the request on behalf of. Alternative to `teamId` for identifying the team. */
        slug?: components['parameters']['Slug'];
      };
      header?: {
        /** @description The continuous integration or delivery environment where this artifact operation is being performed. Examples: `github-actions`, `circleci`, `jenkins`. */
        'x-artifact-client-ci'?: components['parameters']['ArtifactClientCI'];
        /** @description Indicates whether the client is running in an interactive shell. `1` for interactive, `0` for non-interactive (CI/scripts). */
        'x-artifact-client-interactive'?: components['parameters']['ArtifactClientInteractive'];
      };
      path: {
        /** @description The artifact hash. This is a content-addressable hash that uniquely identifies the cached artifact based on task inputs. */
        hash: components['parameters']['ArtifactHash'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Artifact downloaded successfully */
      200: {
        headers: {
          /** @description The size of the artifact in bytes */
          'Content-Length'?: number;
          /** @description The time taken to generate the artifact in milliseconds */
          'x-artifact-duration'?: number;
          /** @description The signature/tag of the artifact for verification. This value was provided during upload and can be used by the client to verify artifact integrity. */
          'x-artifact-tag'?: string;
          [name: string]: unknown;
        };
        content: {
          'application/octet-stream': string;
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['ArtifactNotFound'];
    };
  };
  uploadArtifact: {
    parameters: {
      query?: {
        /** @description The team identifier to perform the request on behalf of. Used for multi-tenant cache implementations where artifacts are scoped to teams. */
        teamId?: components['parameters']['TeamId'];
        /** @description The team slug to perform the request on behalf of. Alternative to `teamId` for identifying the team. */
        slug?: components['parameters']['Slug'];
      };
      header: {
        /** @description The artifact size in bytes */
        'Content-Length': number;
        /** @description The time taken to generate the artifact in milliseconds. This value is stored and returned when the artifact is downloaded. */
        'x-artifact-duration'?: number;
        /** @description A base64-encoded tag for this artifact, typically used for verification. This value is stored and returned when the artifact is downloaded via the `x-artifact-tag` response header. */
        'x-artifact-tag'?: string;
        /** @description The continuous integration or delivery environment where this artifact operation is being performed. Examples: `github-actions`, `circleci`, `jenkins`. */
        'x-artifact-client-ci'?: components['parameters']['ArtifactClientCI'];
        /** @description Indicates whether the client is running in an interactive shell. `1` for interactive, `0` for non-interactive (CI/scripts). */
        'x-artifact-client-interactive'?: components['parameters']['ArtifactClientInteractive'];
      };
      path: {
        /** @description The artifact hash. This is a content-addressable hash that uniquely identifies the cached artifact based on task inputs. */
        hash: components['parameters']['ArtifactHash'];
      };
      cookie?: never;
    };
    /** @description The artifact data as a gzip-compressed tarball */
    requestBody: {
      content: {
        'application/octet-stream': string;
      };
    };
    responses: {
      /** @description Artifact uploaded successfully (alternative success response) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ArtifactUploadResponse'];
        };
      };
      /** @description Artifact accepted for storage */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ArtifactUploadResponse'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
    };
  };
  artifactExists: {
    parameters: {
      query?: {
        /** @description The team identifier to perform the request on behalf of. Used for multi-tenant cache implementations where artifacts are scoped to teams. */
        teamId?: components['parameters']['TeamId'];
        /** @description The team slug to perform the request on behalf of. Alternative to `teamId` for identifying the team. */
        slug?: components['parameters']['Slug'];
      };
      header?: never;
      path: {
        /** @description The artifact hash. This is a content-addressable hash that uniquely identifies the cached artifact based on task inputs. */
        hash: components['parameters']['ArtifactHash'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Artifact exists */
      200: {
        headers: {
          /** @description The size of the artifact in bytes */
          'Content-Length'?: number;
          /** @description The time taken to generate the artifact in milliseconds (if stored) */
          'x-artifact-duration'?: number;
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['ArtifactNotFound'];
    };
  };
  queryArtifacts: {
    parameters: {
      query?: {
        /** @description The team identifier to perform the request on behalf of. Used for multi-tenant cache implementations where artifacts are scoped to teams. */
        teamId?: components['parameters']['TeamId'];
        /** @description The team slug to perform the request on behalf of. Alternative to `teamId` for identifying the team. */
        slug?: components['parameters']['Slug'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ArtifactQueryRequest'];
      };
    };
    responses: {
      /** @description Artifact information retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ArtifactQueryResponse'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
    };
  };
  recordCacheEvents: {
    parameters: {
      query?: {
        /** @description The team identifier to perform the request on behalf of. Used for multi-tenant cache implementations where artifacts are scoped to teams. */
        teamId?: components['parameters']['TeamId'];
        /** @description The team slug to perform the request on behalf of. Alternative to `teamId` for identifying the team. */
        slug?: components['parameters']['Slug'];
      };
      header?: {
        /** @description The continuous integration or delivery environment where this artifact operation is being performed. Examples: `github-actions`, `circleci`, `jenkins`. */
        'x-artifact-client-ci'?: components['parameters']['ArtifactClientCI'];
        /** @description Indicates whether the client is running in an interactive shell. `1` for interactive, `0` for non-interactive (CI/scripts). */
        'x-artifact-client-interactive'?: components['parameters']['ArtifactClientInteractive'];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CacheEvent'][];
      };
    };
    responses: {
      /** @description Events recorded successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
    };
  };
}
